### ISSUE TITLE
Settings not saved/possible to set new defaults?

### ISSUE THREAD

**Issue by canalnoises** [jtfrey/uvc-util#15]
The controls I set with uvc-util don't stick around after I disconnect and reconnect my webcam. Is this typical behavior, and if not, any ideas why it's resetting to the defaults? I'm running macOS 10.14.6 and using a Microsoft LifeCam HD-3000. 

If that is expected behavior is there a way to set new defaults with uvc-util? I have a script I can run to set everything how I want it, but it would of course be nice to not have to worry about that at all.

Thanks!

**Comment by jtfrey** [comment]
If the camera doesn't retain state, then that's an issue with the camera, IMO.  You could always put the `uvc-util` commands to setup the state in a shell script and just execute that when you connect the camera.  Since `uvc-util` isn't a daemon that constantly monitors for cameras to appear it really doesn't have a way of introducing behavior to auto-apply config changes on events.

**Comment by canalnoises** [comment]
That makes sense. Thanks for the reply!
